FROM ubuntu:24.04

RUN \
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get update && apt-get upgrade -y && \
  apt-get install -y \
    lsb-release \
    gnupg \
    make \
    git \
    libtest-differences-perl \
    sudo \
    wget \
    apt-utils \
    tzdata \
    wget \
    curl \
    libpcre3-dev \
    uuid-dev \
    libmagic-dev \
    pkg-config \
    g++ \
    flex \
    bison \
    zlib1g-dev \
    libffi-dev \
    gettext \
    libgeoip-dev \
    libjson-perl \
    libbz2-dev \
    libwww-perl \
    libpng-dev \
    xz-utils \
    libffi-dev \
    libssl-dev \
    libreadline-dev \
    libtool \
    libyaml-dev \
    dh-autoreconf \
    libsocket6-perl \
    libtest-differences-perl \
    libmaxminddb-dev \
    libcurl4-openssl-dev \
    libyara-dev \
    libglib2.0-dev \
    libpcap-dev \
    libnghttp2-dev \
    liblua5.4-dev \
    librdkafka-dev \
    libzstd-dev && \
  rm -rf /var/lib/apt/lists/*

ARG USERNAME=arkime
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME -s /usr/bin/bash \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

RUN sudo mkdir -p /workspace /opt/arkime && \
    sudo chown ${USER_UID}:${USER_GID} /workspace /opt/arkime

WORKDIR /workspace

